"""
Full team name lookup for fuzzy-matching Kalshi/Polymarket market titles.
Each entry is a list of names/aliases to search for (case-insensitive).
"""

TEAM_NAMES: dict[str, dict[str, list[str]]] = {
    "nba": {
        "ATL": ["Atlanta Hawks", "Hawks"],
        "BOS": ["Boston Celtics", "Celtics"],
        "BKN": ["Brooklyn Nets", "Nets"],
        "CHA": ["Charlotte Hornets", "Hornets"],
        "CHI": ["Chicago Bulls", "Bulls"],
        "CLE": ["Cleveland Cavaliers", "Cavaliers", "Cavs"],
        "DAL": ["Dallas Mavericks", "Mavericks", "Mavs"],
        "DEN": ["Denver Nuggets", "Nuggets"],
        "DET": ["Detroit Pistons", "Pistons"],
        "GSW": ["Golden State Warriors", "Warriors"],
        "HOU": ["Houston Rockets", "Rockets"],
        "IND": ["Indiana Pacers", "Pacers"],
        "LAC": ["Los Angeles Clippers", "LA Clippers", "Clippers"],
        "LAL": ["Los Angeles Lakers", "LA Lakers", "Lakers"],
        "MEM": ["Memphis Grizzlies", "Grizzlies"],
        "MIA": ["Miami Heat", "Heat"],
        "MIL": ["Milwaukee Bucks", "Bucks"],
        "MIN": ["Minnesota Timberwolves", "Timberwolves", "Wolves"],
        "NOP": ["New Orleans Pelicans", "Pelicans"],
        "NYK": ["New York Knicks", "Knicks"],
        "OKC": ["Oklahoma City Thunder", "Thunder"],
        "ORL": ["Orlando Magic", "Magic"],
        "PHI": ["Philadelphia 76ers", "76ers", "Sixers"],
        "PHO": ["Phoenix Suns", "Suns"],
        "POR": ["Portland Trail Blazers", "Trail Blazers", "Blazers"],
        "SAC": ["Sacramento Kings", "Kings"],
        "SAS": ["San Antonio Spurs", "Spurs"],
        "TOR": ["Toronto Raptors", "Raptors"],
        "UTA": ["Utah Jazz", "Jazz"],
        "WAS": ["Washington Wizards", "Wizards"],
    },
    "nfl": {
        "ARI": ["Arizona Cardinals", "Cardinals"],
        "ATL": ["Atlanta Falcons", "Falcons"],
        "BAL": ["Baltimore Ravens", "Ravens"],
        "BUF": ["Buffalo Bills", "Bills"],
        "CAR": ["Carolina Panthers", "Panthers"],
        "CHI": ["Chicago Bears", "Bears"],
        "CIN": ["Cincinnati Bengals", "Bengals"],
        "CLE": ["Cleveland Browns", "Browns"],
        "DAL": ["Dallas Cowboys", "Cowboys"],
        "DEN": ["Denver Broncos", "Broncos"],
        "DET": ["Detroit Lions", "Lions"],
        "GB":  ["Green Bay Packers", "Packers"],
        "HOU": ["Houston Texans", "Texans"],
        "IND": ["Indianapolis Colts", "Colts"],
        "JAX": ["Jacksonville Jaguars", "Jaguars"],
        "KC":  ["Kansas City Chiefs", "Chiefs"],
        "LAC": ["Los Angeles Chargers", "LA Chargers", "Chargers"],
        "LAR": ["Los Angeles Rams", "LA Rams", "Rams"],
        "LV":  ["Las Vegas Raiders", "Raiders"],
        "MIA": ["Miami Dolphins", "Dolphins"],
        "MIN": ["Minnesota Vikings", "Vikings"],
        "NE":  ["New England Patriots", "Patriots"],
        "NO":  ["New Orleans Saints", "Saints"],
        "NYG": ["New York Giants", "Giants"],
        "NYJ": ["New York Jets", "Jets"],
        "PHI": ["Philadelphia Eagles", "Eagles"],
        "PIT": ["Pittsburgh Steelers", "Steelers"],
        "SEA": ["Seattle Seahawks", "Seahawks"],
        "SF":  ["San Francisco 49ers", "49ers"],
        "TB":  ["Tampa Bay Buccaneers", "Buccaneers", "Bucs"],
        "TEN": ["Tennessee Titans", "Titans"],
        "WAS": ["Washington Commanders", "Commanders"],
    },
    "mlb": {
        "AZ":  ["Arizona Diamondbacks", "Diamondbacks", "D-backs"],
        "ATL": ["Atlanta Braves", "Braves"],
        "BAL": ["Baltimore Orioles", "Orioles"],
        "BOS": ["Boston Red Sox", "Red Sox"],
        "CHC": ["Chicago Cubs", "Cubs"],
        "CWS": ["Chicago White Sox", "White Sox"],
        "CIN": ["Cincinnati Reds", "Reds"],
        "CLE": ["Cleveland Guardians", "Guardians"],
        "COL": ["Colorado Rockies", "Rockies"],
        "DET": ["Detroit Tigers", "Tigers"],
        "HOU": ["Houston Astros", "Astros"],
        "KC":  ["Kansas City Royals", "Royals"],
        "LAA": ["Los Angeles Angels", "Angels"],
        "LAD": ["Los Angeles Dodgers", "Dodgers"],
        "MIA": ["Miami Marlins", "Marlins"],
        "MIL": ["Milwaukee Brewers", "Brewers"],
        "MIN": ["Minnesota Twins", "Twins"],
        "NYM": ["New York Mets", "Mets"],
        "NYY": ["New York Yankees", "Yankees"],
        "ATH": ["Oakland Athletics", "Athletics", "A's"],
        "PHI": ["Philadelphia Phillies", "Phillies"],
        "PIT": ["Pittsburgh Pirates", "Pirates"],
        "SD":  ["San Diego Padres", "Padres"],
        "SF":  ["San Francisco Giants", "Giants"],
        "SEA": ["Seattle Mariners", "Mariners"],
        "STL": ["St. Louis Cardinals", "Cardinals"],
        "TB":  ["Tampa Bay Rays", "Rays"],
        "TEX": ["Texas Rangers", "Rangers"],
        "TOR": ["Toronto Blue Jays", "Blue Jays"],
        "WSH": ["Washington Nationals", "Nationals"],
    },
    "epl": {
        "ARS": ["Arsenal"],
        "AVL": ["Aston Villa"],
        "BOU": ["Bournemouth"],
        "BRE": ["Brentford"],
        "BHA": ["Brighton"],
        "BRN": ["Burnley"],
        "CHE": ["Chelsea"],
        "CRY": ["Crystal Palace"],
        "EVE": ["Everton"],
        "FUL": ["Fulham"],
        "LIV": ["Liverpool"],
        "LEE": ["Leeds United", "Leeds"],
        "MCI": ["Manchester City", "Man City"],
        "MUN": ["Manchester United", "Man Utd", "Man United"],
        "NEW": ["Newcastle United", "Newcastle"],
        "NFO": ["Nottingham Forest"],
        "SHU": ["Sheffield United"],
        "TOT": ["Tottenham Hotspur", "Tottenham", "Spurs"],
        "WHU": ["West Ham United", "West Ham"],
        "WOL": ["Wolverhampton Wanderers", "Wolves"],
    },
    "wnba": {
        "ATL": ["Atlanta Dream", "Dream"],
        "CHI": ["Chicago Sky", "Sky"],
        "CON": ["Connecticut Sun", "Sun"],
        "DAL": ["Dallas Wings", "Wings"],
        "GSV": ["Golden State Valkyries", "Valkyries"],
        "IND": ["Indiana Fever", "Fever"],
        "LAS": ["Los Angeles Sparks", "Sparks"],
        "LVA": ["Las Vegas Aces", "Aces"],
        "MIN": ["Minnesota Lynx", "Lynx"],
        "NYL": ["New York Liberty", "Liberty"],
        "PHX": ["Phoenix Mercury", "Mercury"],
        "SEA": ["Seattle Storm", "Storm"],
        "WAS": ["Washington Mystics", "Mystics"],
    },
}


def get_aliases(league: str, code: str) -> list[str]:
    return TEAM_NAMES.get(league.lower(), {}).get(code.upper(), [code])


def team_in_text(league: str, code: str, text: str) -> bool:
    t = text.lower()
    for name in get_aliases(league, code):
        if name.lower() in t:
            return True
    return False
